import type { AnalysisResult } from '../types';

/**
 * Format Briefing to Markdown
 */
export function formatAsMarkdown(result: AnalysisResult): string {
  const lines: string[] = [];

  lines.push(`# MISSED. — Catch-Up Intelligence Briefing`);
  lines.push(`Generated: ${new Date(result.analyzedAt).toLocaleString()}`);
  lines.push(`Method: Local Heuristic Analysis (100% In-Browser, Zero Cloud Transmission)`);
  lines.push(`Total Messages Analyzed: ${result.stats.totalMessages}`);
  lines.push(`Active Participants: ${result.stats.participants.join(', ') || 'N/A'}`);
  lines.push('');

  lines.push(`## 📌 Executive Summary`);
  result.summary.forEach(bullet => {
    lines.push(`- ${bullet}`);
  });
  lines.push('');

  const urgentItems = result.items.filter(i => i.priority === 'urgent');
  if (urgentItems.length > 0) {
    lines.push(`## 🚨 Urgent & Act Now (${urgentItems.length})`);
    urgentItems.forEach(item => {
      lines.push(`### [${item.priority.toUpperCase()}] ${item.title}`);
      lines.push(`- **Sender**: ${item.sender} ${item.timestamp ? `(${item.timestamp})` : ''}`);
      lines.push(`- **Why it matters**: ${item.explanation}`);
      if (item.deadline) {
        lines.push(`- **Deadline**: ${item.deadline.dateStr} [${item.deadline.status}]`);
      }
      lines.push(`- **Source Excerpt**: *"${item.sourceMessageExcerpt}"* [Ref: ${item.sourceMessageId}]`);
      lines.push(`- **Status**: ${item.isCompleted ? 'Completed ✅' : 'Open ⏳'}`);
      lines.push('');
    });
  }

  const deadlines = result.items.filter(i => i.category === 'deadline');
  if (deadlines.length > 0) {
    lines.push(`## ⏰ Deadlines & Milestones (${deadlines.length})`);
    deadlines.forEach(item => {
      lines.push(`- **${item.deadline?.dateStr || item.title}**: ${item.explanation} (Sender: ${item.sender}, Source: ${item.sourceMessageId})`);
    });
    lines.push('');
  }

  const decisions = result.items.filter(i => i.category === 'decision');
  if (decisions.length > 0) {
    lines.push(`## ⚖️ Confirmed Decisions (${decisions.length})`);
    decisions.forEach(item => {
      lines.push(`- **${item.title}**: Confirmed by ${item.sender}. Source: "${item.sourceMessageExcerpt}" [Ref: ${item.sourceMessageId}]`);
    });
    lines.push('');
  }

  const mentions = result.items.filter(i => i.category === 'mention');
  if (mentions.length > 0) {
    lines.push(`## 👤 You Were Mentioned (${mentions.length})`);
    mentions.forEach(item => {
      lines.push(`- **From ${item.sender}**: ${item.title} — "${item.sourceMessageExcerpt}" [Ref: ${item.sourceMessageId}]`);
    });
    lines.push('');
  }

  const waitingOn = result.items.filter(i => i.category === 'question' && i.isWaitingOn);
  if (waitingOn.length > 0) {
    lines.push(`## ❓ Waiting On & Unanswered Queries (${waitingOn.length})`);
    waitingOn.forEach(item => {
      lines.push(`- **From ${item.sender}**: ${item.title} [Ref: ${item.sourceMessageId}]`);
    });
    lines.push('');
  }

  const updates = result.items.filter(i => i.category === 'update');
  if (updates.length > 0) {
    lines.push(`## 📢 Important Updates (${updates.length})`);
    updates.forEach(item => {
      lines.push(`- **${item.title}**: ${item.explanation} [Ref: ${item.sourceMessageId}]`);
    });
    lines.push('');
  }

  lines.push(`---`);
  lines.push(`*Generated by MISSED. — "Catch up on what matters. Keep your chats yours."*`);

  return lines.join('\n');
}

/**
 * Format Briefing to Plain Text
 */
export function formatAsPlainText(result: AnalysisResult): string {
  const lines: string[] = [];

  lines.push(`=======================================================`);
  lines.push(`MISSED. — Catch-Up Intelligence Briefing`);
  lines.push(`Generated: ${new Date(result.analyzedAt).toLocaleString()}`);
  lines.push(`Method: Local Heuristic Engine (In-Browser Privacy)`);
  lines.push(`=======================================================\n`);

  lines.push(`EXECUTIVE SUMMARY:`);
  result.summary.forEach((b, i) => {
    lines.push(` [${i + 1}] ${b}`);
  });
  lines.push('');

  lines.push(`ACT NOW / URGENT ITEMS:`);
  result.items.filter(i => i.priority === 'urgent' || i.category === 'task').forEach(item => {
    lines.push(`* [${item.priority.toUpperCase()}] ${item.title}`);
    lines.push(`  Why: ${item.explanation}`);
    lines.push(`  From: ${item.sender} | Ref: ${item.sourceMessageId} | Done: ${item.isCompleted ? 'YES' : 'NO'}`);
  });
  lines.push('');

  lines.push(`DECISIONS:`);
  result.items.filter(i => i.category === 'decision').forEach(item => {
    lines.push(`* ${item.title} (Confirmed by ${item.sender})`);
  });
  lines.push('');

  lines.push(`DEADLINES:`);
  result.items.filter(i => i.category === 'deadline').forEach(item => {
    lines.push(`* ${item.deadline?.dateStr}: ${item.title}`);
  });
  lines.push('');

  return lines.join('\n');
}

/**
 * Trigger file download in browser
 */
export function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
